import SwiftUI

// MARK: - Cyclometer Design Tokens
// Primary brand : #60BD10 (Cyclometer green)
// Token prefix  : cy  (Cyclometer)
// Theme         : Dark-primary, outdoor sunlight optimised
// Contrast      : WCAG AA+ on all foreground/background pairs
//
// Per-token `Color.cy*` accessors are auto-generated by Xcode from the
// asset catalog (Assets.xcassets). This file only declares semantic helpers.

// MARK: - Semantic Helpers

extension Color {
    /// HR zone colour for zone 1–5. Returns cyTextTertiary for out-of-range values.
    static func hrZone(_ zone: Int) -> Color {
        switch zone {
        case 1: return Color("cyHRZone1")
        case 2: return Color("cyHRZone2")
        case 3: return Color("cyHRZone3")
        case 4: return Color("cyHRZone4")
        case 5: return Color("cyHRZone5")
        default: return Color("cyTextTertiary")
        }
    }

    /// Foreground rating colour for a normalised score (0.0–1.0).
    static func rating(score: Double) -> Color {
        score < 0.33 ? Color("cyRatingBad")
            : score < 0.66 ? Color("cyRatingOkay")
            : Color("cyRatingGood")
    }

    /// Background tint for a normalised score (0.0–1.0).
    static func ratingBackground(score: Double) -> Color {
        score < 0.33 ? Color("cyRatingBadBg")
            : score < 0.66 ? Color("cyRatingOkayBg")
            : Color("cyRatingGoodBg")
    }

    /// Route hill-grade colour for a slope percentage. Bands: <3 flat, <6, <9,
    /// <12, ≥12 (extreme). Used for steepness colour-coding on the route
    /// polyline (M8); see `mapRoute` / `mapTravelPath` for the base map lines.
    static func mapGrade(percent: Double) -> Color {
        switch percent {
        case ..<3:  return Color("cyMapGrade1")
        case ..<6:  return Color("cyMapGrade2")
        case ..<9:  return Color("cyMapGrade3")
        case ..<12: return Color("cyMapGrade4")
        default:    return Color("cyMapGrade5")
        }
    }
}
